### ISSUE TITLE
export data to an aleph instance

### ISSUE THREAD

**Issue by thimios** [pudo/opensanctions#129]
I know that I could use the command line alephclient tool to export datasets to an aleph instance, but is there a nice way to export data to an aleph instance within each crawler run?

In the previous framework, I was using the aggregator section in the crawler's configuration while having ALEPHCLIENT_API_KEY and ALEPHCLIENT_HOST exported in the container:

```
name: eu_fsf
description: "[OSANC] Financial Sanctions Files (FSF) published by EU Commision"
schedule: daily
expire: 1
pipeline:
  init:
    method: seed
    params:
      url: 'https://webgate.ec.europa.eu/europeaid/fsd/fsf/public/files/xmlFullSanctionsList_1_1/content?token=n00378os'
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.eu_fsf:fsf_parse
aggregator:
  method: ftmstore.memorious:ftm_load_aleph
```

Can we use something similar to export data to aleph with the new framework?
